#!/usr/bin/python
# typeset text nicely for paginating

# This program takes in a prose text file where each line is a paragraph.
# It first looks for a bibliography section, which is titled 'REFERENCES', 'WORKS CITED', or 'BIBLIOGRAPHY'.
# It then
# Note each line is treated independently.
import getopt
import stat
import os
import sys
import string


short_options = "hv"
long_options = [
    "help",
    "version",
]

try:
    options, positional_arguments = getopt.gnu_getopt(
        sys.argv[1:], short_options, long_options
    )
except getopt.GetoptError as error:
    print(f"bib: '-{error.opt}': Option not recognized", file=sys.stderr)
    sys.exit(1)

for option in options:
    argument = option[1]
    option = option[0]

    if option == "-h" or option == "--help":
        print("Usage: bib [OPTION]... [FILE]")
        print(
            "Insert inline citations for references and works cited from a bibliography."
        )
        sys.exit(0)
    elif option == "-v" or option == "--version":
        print("bib (Typset) v1.0.0")
        sys.exit(0)

if not positional_arguments:
    if stat.S_ISFIFO(os.fstat(0).st_mode):
        input_file = "-"
    else:
        print("bib: Missing operand", file=sys.stderr)
        sys.exit(1)
else:
    if len(positional_arguments) > 1:
        print("bib: Too many arguments", file=sys.stderr)
        sys.exit(1)
    else:
        input_file = positional_arguments[0]

if input_file == "-":
    all_lines = sys.stdin.read().splitlines()
else:
    if os.path.isfile(input_file):
        pass
    elif os.path.isfile(f"{os.getcwd}/{input_file}"):
        input_file = f"{os.getcwd}/{input_file}"
    elif os.path.isdir(input_file) or os.path.isdir(f"{os.getcwd}/{input_file}"):
        print(f"bib: {input_file}: Is a directory", file=sys.stderr)
        sys.exit(1)
    else:
        print(f"bib: {input_file}: No such file or directory", file=sys.stderr)
        sys.exit(1)

    with open(input_file, mode="r", encoding="utf8") as text_file:
        all_lines = text_file.read().splitlines()

found_bibliography = False
for index, line in enumerate(all_lines):
    if line.strip() in ["BIBLIOGRAPHY", "REFERENCES", "WORKS CITED"]:
        found_bibliography = index + 1

bibliography = {}
end_bibliography = found_bibliography
if found_bibliography is not False:
    for index, line in enumerate(all_lines[found_bibliography:]):
        if line := line.strip():
            if line != line.upper():
                bibliography[index + 1] = (line.split("|")[0], line.split("|")[1])
            else:
                end_bibliography += index
                break
    else:
        end_bibliography = len(all_lines)
else:
    for line in all_lines:
        print(line)

for line in all_lines[0:found_bibliography]:
    for index, short_form in enumerate([bibliography[key][0] for key in bibliography]):
        index += 1
        line = line.replace(f"[[{index}]]", short_form)
    print(line)

try:
    lines = [
        line.split("|")[1] for line in all_lines[found_bibliography:end_bibliography]
    ]
except IndexError:
    print("bib: parse error", file=sys.stderr)
    sys.exit(1)

if lines:
    print("\n".join(sorted(lines)))

for line in all_lines[end_bibliography:]:
    for index, short_form in enumerate([bibliography[key][0] for key in bibliography]):
        index += 1
        print(line.replace(f"[[{index}]]", short_form))
