#!/usr/bin/python
# paginate text into pages

# This program takes in a prose text file where each line is assumed to be less than the width of the page.
# Use a typesetter like `typ`, `fmt`, or `fold` to achieve this
# It then outputs a modified text file, where pages are separated by formfeeds and each has a header.
import datetime
import getopt
import math
import stat
import os
import sys

HEADER_MODE = True
NAME = "Page"
TODAY = datetime.date.today()

FIRST_PAGE_NUMBER = False
PAGE_LENGTH = 66
# These two are only used for right-aligning page number
VERTICAL_MARGIN = 1
PAGE_WIDTH = 84
MARGIN_WIDTH = 1

TITLE_LINES = 0

short_options = "D:HL:M:n:N:T:V:w:hv"
long_options = [
    "date=",
    "no-header-mode",
    "page-length=",
    "margin-width=",
    "first-page-number=",
    "name",
    "vertical-margin=",
    "title-page=",
    "page-width=",
    "help",
    "version",
]

try:
    options, positional_arguments = getopt.gnu_getopt(
        sys.argv[1:], short_options, long_options
    )
except getopt.GetoptError as error:
    print(f"pag: '-{error.opt}': Option not recognized", file=sys.stderr)
    sys.exit(1)

for option in options:
    argument = option[1]
    option = option[0]

    if option == "-h" or option == "--help":
        print("Usage: pag [OPTION]... [FILE]")
        print("Paginate a document")
        sys.exit(0)
    elif option == "-v" or option == "--version":
        print("pag (Typset) v2.1.0")
        sys.exit(0)
    elif option == "-D" or option == "--date":
        TODAY = datetime.date.fromisoformat(argument)
    elif option == "-H" or option == "--no-header-mode":
        HEADER_MODE = False
    elif option == "-L" or option == "--page-length":
        try:
            PAGE_LENGTH = int(argument)
            if PAGE_LENGTH < 2:
                raise ValueError
        except ValueError:
            print(f"pag: '{PAGE_LENGTH}': Invalid page length", file=sys.stderr)
            sys.exit(1)
    elif option == "-M" or option == "--margin-width":
        try:
            MARGIN_WIDTH = int(argument)
            if MARGIN_WIDTH < 0:
                raise ValueError
        except ValueError:
            print(f"pag: '{MARGIN_WIDTH}': Invalid page length", file=sys.stderr)
            sys.exit(1)
    elif option == "-n" or option == "--first-page-number":
        try:
            FIRST_PAGE_NUMBER = int(argument)
        except ValueError:
            print(f"pag: '{FIRST_PAGE_NUMBER}': Invalid page number", file=sys.stderr)
            sys.exit(1)
    elif option == "-N" or option == "--name":
        NAME = argument.strip()
    elif option == "-V" or option == "--vertical-margin":
        try:
            VERTICAL_MARGIN = int(argument)
            if VERTICAL_MARGIN < 0:
                raise ValueError
        except ValueError:
            print(f"pag: '{VERTICAL_MARGIN}': Invalid vertical margin", file=sys.stderr)
            sys.exit(1)
    elif option == "-T" or option == "--title-page":
        TITLE_LINES = int(argument)
    elif option == "-w" or option == "--page-width":
        try:
            PAGE_WIDTH = int(argument)
            if PAGE_WIDTH < 8:
                raise ValueError
        except ValueError:
            print(f"pag: '{PAGE_WIDTH}': Invalid page width", file=sys.stderr)
            sys.exit(1)

if FIRST_PAGE_NUMBER is False:
    FIRST_PAGE_NUMBER = 0 if TITLE_LINES else 1

if PAGE_LENGTH < 10:
    HEADER_MODE = False

# Remove lines for bottom and top margins, plus one extra line at the bottom
PAGE_LENGTH -= (MARGIN_WIDTH * 2) - 1

if not positional_arguments:
    if stat.S_ISFIFO(os.fstat(0).st_mode):
        input_file = "-"
    else:
        print("pag: Missing operand", file=sys.stderr)
        sys.exit(1)
else:
    if len(positional_arguments) > 1:
        print("pag: Too many arguments", file=sys.stderr)
        sys.exit(1)
    else:
        input_file = positional_arguments[0]

if input_file == "-":
    all_lines = sys.stdin.read().splitlines()
else:
    if os.path.isfile(input_file):
        pass
    elif os.path.isfile(f"{os.getcwd}/{input_file}"):
        input_file = f"{os.getcwd}/{input_file}"
    elif os.path.isdir(input_file) or os.path.isdir(f"{os.getcwd}/{input_file}"):
        print(f"pag: {input_file}: Is a directory", file=sys.stderr)
        sys.exit(1)
    else:
        print(f"pag: {input_file}: No such file or directory", file=sys.stderr)
        sys.exit(1)

    with open(input_file, mode="r", encoding="utf8") as text_file:
        all_lines = text_file.read().splitlines()


def roman_numeral(num: int) -> str:
    chars = {
        1: "I",
        5: "V",
        10: "X",
        50: "L",
        100: "C",
        500: "D",
        1000: "M",
        5000: "G",
        10000: "H",
    }

    if not isinstance(num, int):
        raise TypeError

    numeral = ""

    power = 10 ** int(math.log10(num))
    while num:
        most_significant_digit = int(num / power)

        if most_significant_digit <= 3:
            numeral += chars[power] * most_significant_digit
        elif most_significant_digit == 4:
            numeral += chars[power] + chars[power * 5]
        elif 5 <= most_significant_digit <= 8:
            numeral += chars[power * 5] + chars[power] * (most_significant_digit - 5)
        elif most_significant_digit == 9:
            numeral += chars[power] + chars[power * 10]

        num = int(num / 10)
    return numeral


def get_page_number_str(page_number: int):
    if not page_number:
        return ""
    elif page_number > 0:
        return str(page_number)
    else:
        return roman_numeral(abs(FIRST_PAGE_NUMBER) + page_number + 1)


# Add vertical centering
if TITLE_LINES:
    for _ in range(
        (PAGE_LENGTH - abs(TITLE_LINES) * (2 if TITLE_LINES < 0 else 1)) // 2
    ):
        print()

page_number = FIRST_PAGE_NUMBER
lines_on_page = 0
in_header = True
for line in all_lines:
    if TITLE_LINES:
        TITLE_LINES += 1 if TITLE_LINES < 0 else -1
        print(line)
        lines_on_page += 1
        if TITLE_LINES < 0:
            print()
            lines_on_page += 1

        if not TITLE_LINES:
            for _ in range((PAGE_LENGTH - lines_on_page) // 2):
                print()
            print("\f", end="")
            lines_on_page = 0
            page_number += 1
        continue

    if HEADER_MODE and in_header:
        if page_number:
            print(
                f"{'\n' * VERTICAL_MARGIN}{' ' * MARGIN_WIDTH}{TODAY.month:>02}/{TODAY.day:>02}/{TODAY.year:>04}{' '*(PAGE_WIDTH - MARGIN_WIDTH * 2 - 10 - len(NAME) - len(get_page_number_str(page_number)))}{NAME} {get_page_number_str(page_number)}\n"
            )
        else:
            print()
        lines_on_page += 1
        in_header = False

    print(line)
    lines_on_page += 1

    if lines_on_page == PAGE_LENGTH or (
        len({char for char in line.strip()}) == 1 and line.strip()[0] == "-"
    ):
        print("\f", end="")
        in_header = True
        lines_on_page = 0
        page_number += 1
